[build]
  command = "npm run build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,SUPABASE_URL" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "next dev"
  targetPort = 3000
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {Role = ["admin"]}
